export let TRIPS = [
  {
    id: 1,
    name: "Ariana soghra",
    price_adult: 60,
    price_child: 3,
    time: "1",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "400",
    thumb: "assets/img/house/thumb/h_1.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [
      "assets/img/trip/thumb/trip_5.jpg",
      "assets/img/trip/thumb/trip_6.jpg",
      "assets/img/trip/thumb/trip_7.jpg",
      "assets/img/trip/thumb/trip_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ],
    date: "Fri Apr 26 2019 15:20:31 GMT+2",
    owner:"0x13321s3qd1sqd321qsdq321qsd",
    buyer:"0xqe54a6z54eas5d13qsd15q1",
    bank:"0xqsqd35q1s3d21a5z1d3a2dqsd",
    insurance:"0xq654d65s12qs1da5zdaazd",
    house:"1",
    loan:"5000",
    forBank:"10",
    forInsurance:"2",
    advance:"200"
  },
  {
    id: 2,
    name: "Monastir, Jemmal",
    price_adult: 90,
    price_child: 5,
    time: "2",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "500",
    thumb: "assets/img/house/thumb/h_2.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [],
    highlights: [],
    date: "Fri Apr 26 2019 15:20:31 GMT+2",
    owner:"0x13321s3qd1sqd321qsdq321qsd",
    buyer:"0xqe54a6z54eas5d13qsd15q1",
    bank:"0xqsqd35q1s3d21a5z1d3a2dqsd",
    insurance:"0xq654d65s12qs1da5zdaazd",
    house:"1",
    loan:"5000",
    forBank:"10",
    forInsurance:"2",
    advance:"200"
  },
  {
    id: 3,
    name: "Sousse, Sahloul",
    price_adult: 100,
    price_child: 2,
    time: "3",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "150",
    thumb: "assets/img/house/thumb/h_3.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "São Paulo, Brazil",
    images: [],
    highlights: [],
    date: "Fri Apr 26 2019 15:20:31 GMT+2",
    owner:"0x13321s3qd1sqd321qsdq321qsd",
    buyer:"0xqe54a6z54eas5d13qsd15q1",
    bank:"0xqsqd35q1s3d21a5z1d3a2dqsd",
    insurance:"0xq654d65s12qs1da5zdaazd",
    house:"1",
    loan:"5000",
    forBank:"10",
    forInsurance:"2",
    advance:"200"
  },
  {
    id: 4,
    name: "Sfax",
    price_adult: 200,
    price_child: 3,
    time: "4",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "300",
    thumb: "assets/img/house/thumb/h_4.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [],
    highlights: [],
    date: "Fri Apr 26 2019 15:20:31 GMT+2",
    owner:"0x13321s3qd1sqd321qsdq321qsd",
    buyer:"0xqe54a6z54eas5d13qsd15q1",
    bank:"0xqsqd35q1s3d21a5z1d3a2dqsd",
    insurance:"0xq654d65s12qs1da5zdaazd",
    house:"1",
    loan:"5000",
    forBank:"10",
    forInsurance:"2",
    advance:"200"
  }
]
